version: "3.0"
#This file combines all the edge services and our services so that it can be deployed as a unit
services:
  opcua-simulator:
    image: "predixadoption/predix-edge-opcua-simulator:1.0.6"
    networks:
      - predix-edge-broker_net
    ports:
      - 4334:4334
  opcua:
    image: "dtr.predix.io/predix-edge/protocol-adapter-opcua:amd64-1.1.0"
    environment:
      config: "/config/config-opcua.json"
    networks:
      - predix-edge-broker_net
  cloud_gateway_timeseries:
    image: "dtr.predix.io/predix-edge/cloud-gateway:amd64-1.1.0"
    environment:
      config: "/config/config-cloud-gateway.json"
      http_proxy: ""
      https_proxy: "$http_proxy"
      HTTP_PROXY: "$http_proxy"
      HTTPS_PROXY: "$http_proxy"
    networks:
      - predix-edge-broker_net
  predix-edge-node-red:
    image: "predixadoption/predix-edge-node-red:1.0.18"
    networks:
      - predix-edge-broker_net
    ports:
      - 1880:1880
  predix-edge-ref-app:
    image: "predixadoption/predix-edge-ref-app:1.0.38"
    networks:
      - predix-edge-broker_net
    ports:
      - 5000:5000
      - 9002:9002
networks:
  predix-edge-broker_net:
    external: true
